#!/bin/bash -f
. /home/gempak/NAWIPS/Gemenviron.profile
rm -rf model_data.dat

# list of every $MODEL type
dump=$(./gdinv-files)

for var in $dump
do

# files not 0 size, pick one
gdfile=$(find $MODEL -name $var -size +10k |head -1)

# use def. input, doesn't matter, just print navigation and # grids
gdinfo << EOF
gdfile  = $gdfile
GDATTIM = first
GFUNC   = tmpk
GLEVEL  = 0
GVCORD  = none
OUTPUT  = f/data.dat
r
 
e
EOF
gpend

# format / dump to file
cat data.dat | grep -v ANALYSIS |  grep -v '^[[:space:]]*$' >> model_data.dat
echo "" >> model_data.dat

rm -rf data.dat

done
exit 0
